### ISSUE TITLE
Dont work on Ubuntu 18.04

### ISSUE THREAD

**Issue by emmi007** [SlaSerX/FullIPTV#1]
Hi, i have a fresh ubuntu 18.04 where the script doesn't work.
at the start it gives this error:
Ver Cluster Port Status Owner    Data directory              Log file
10  main    5432 down   postgres /var/lib/postgresql/10/main /var/log/postgresql                                                                                                                     /postgresql-10-main.log
and after type the ip adress it gives:
PRIVATE IP ADDRESS, if you don't have, same as above : 192.168.0.60
./FullIPTV-v2.sh: line 212: /etc/postgresql/9.3/main/pg_hba.conf: No such file or directory
./FullIPTV-v2.sh: line 213: /etc/postgresql/9.3/main/pg_hba.conf: No such file or directory
./FullIPTV-v2.sh: line 214: /etc/postgresql/9.3/main/pg_hba.conf: No such file or directory
./FullIPTV-v2.sh: line 215: /etc/postgresql/9.3/main/pg_hba.conf: No such file or directory
./FullIPTV-v2.sh: line 217: /etc/postgresql/9.3/main/postgresql.conf: No such file or directory
psql: FATAL:  Peer authentication failed for user "postgres"
cat: /etc/php5/apache2/php.ini: No such file or directory
./FullIPTV-v2.sh: line 252: /etc/php5/apache2/php.ini: No such file or directory
cat: /etc/php5/cli/php.ini: No such file or directory
./FullIPTV-v2.sh: line 256: /etc/php5/cli/php.ini: No such file or directory
---Update---
After end installation and have restarted the server, i get this when trying to access the webinterface on port 8080:
Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at info@fulliptv.com to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.

Apache/2.4.29 (Ubuntu) Server at 192.168.0.60 Port 8080

**Comment by SlaSerX** [comment]
U dont read my post or my recom.. for script work only on Ubuntu 14.04

На сб, 14.07.2018 г., 23:27 emmi007 <notifications@github.com> написа:

**Comment by karim2009** [comment]
Hello good job you have not à version for debian 8
